JWT_SECRET = "2OXV0xbEcsHISNoEEYYeuBOhSDSJEfB1cXmna9hqfUnzGTLOwWe54KCsrhgz"

JWT_EXPIRES_IN = "90d"

# JSON Web Token secret
# JSON Web Token expiration time
# JSON Web Token cookie expiration time
JWT_COOKIE_EXPIRES_IN = 90

NODE_VERSION = "v16.20.1"

NPM_VERSION = "9.7.1"

NODE_ENV = "devDependencies"

CONTEXT = "dev"

# Node.js version
# NPM version
# NPM dependencies
# name of the deploy context
REPOSITORY_URL = "https://github.com/ThomPoppins/Vind-Expert"

BRANCH = "dev"

SITE_NAME = "vind-expert"
