MONGODB_URI = "mongodb+srv://veldhaasklaas:o59TbydTA9Zd9aNu@chattutorial.guhnq7u.mongodb.net/?retryWrites=true&w=majority"

# Backend for the project base URL
REACT_APP_BACKEND_URL = "https://vind-expertb.netlify.app"

# JSON Web Token secret
JWT_SECRET = "2OXV0xbEcsHISNoEEYYskefjbkjdfbeuBOhSDSJEfB1cXmna9hqfUnzGTLOwWe54KCsrhgz"

# JSON Web Token expiration time
JWT_EXPIRES_IN = "90d"

# JSON Web Token cookie expiration time
JWT_COOKIE_EXPIRES_IN = 90

# Node.js version
NODE_VERSION = "v16.20.1"

# NPM version
NPM_VERSION = "9.7.1"

# NPM dependencies
NODE_ENV = "devDependencies"

# name of the deploy context
CONTEXT = "dev"

REPOSITORY_URL = "https://github.com/ThomPoppins/Vind-Expert"

BRANCH = "main"

SITE_NAME = "vind-expert"
